name: Build linux wheels

on:
  push:
    branches: ["main", "ci", "cibw"]
  pull_request:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout mysqlclient
        uses: actions/checkout@v5
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_PLATFORM: ${{ matrix.platform || 'auto' }}
          CIBW_ARCHS: ${{ matrix.archs || 'auto' }}
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y mysql-devel pkgconfig ||
            apk add mariadb-connector-c-dev ||
            apt install -y default-libmysqlclient-dev pkg-config
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"
          CIBW_TEST_COMMAND: 'python -c "import MySQLdb; print(MySQLdb.version_info)" '
      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*.*
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v5
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        # To test uploads to TestPyPI, uncomment the following:
        with:
          repository-url: https://test.pypi.org/legacy/
